"""Initial schema

Revision ID: 2658e8711c30
Revises: 
Create Date: 2026-05-09 21:37:35.431546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2658e8711c30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('swiggy_access_token', sa.String(), nullable=True),
    sa.Column('swiggy_address_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('reorder_threshold', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('reorder_qty', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('search_query', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_bom',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pos_item_id', sa.String(length=100), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('burn_rate', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['raw_ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_bom')
    op.drop_table('transactions')
    op.drop_table('raw_ingredients')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
