from pydantic import BaseModel
from uuid import UUID

class POSWebhookPayload(BaseModel):
    restaurant_id: UUID
    pos_item_id: str
    quantity: int
    order_value: float
    order_id: str # The POS reference ID
    
class SwiggyAuthPayload(BaseModel):
    restaurant_id: UUID
    code: str              # The temporary auth code from Swiggy
    code_verifier: str     # The raw PKCE secret generated by the frontend